apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: uez869mq6-go-gitops
  description: This is GitOps manifest for uez869mq6-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: uez869mq6-go
    backstage.io/kubernetes-id: uez869mq6-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: uez869mq6-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:uez869mq6-go
